<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<br> <b>Please look to the screenshot - </b>]]>
    </line>
    <line>
      <![CDATA[<br><Strong><font color=#FF0000>--Failed</font></strong>]]>
    </line>
    <line>
      <![CDATA[<a href='../test-output/screenshots/1105154716486purchaseFreeCourseForMySelfFunctionality.png' target='_new'>1105154716486purchaseFreeCourseForMySelfFunctionality.png</a>]]>
    </line>
    <line>
      <![CDATA[<br></br><h3>Failure Reason:</h3>]]>
    </line>
    <line>
      <![CDATA[<br></br>java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
  </reporter-output>
  <suite name="NFHS - Purchase_Course_functionality" duration-ms="37916" started-at="2015-11-05T10:16:40Z" finished-at="2015-11-05T10:17:18Z">
    <groups>
    </groups>
    <test name="purchase free course for MySelf." duration-ms="37916" started-at="2015-11-05T10:16:40Z" finished-at="2015-11-05T10:17:18Z">
      <class name="com.zinghr.login.index.LoginIndex">
        <test-method status="PASS" signature="fetchSuiteConfiguration(org.testng.ITestContext)[pri:0, instance:com.zinghr.login.index.LoginIndex@6aaa5eb0]" name="fetchSuiteConfiguration" is-config="true" duration-ms="15" started-at="2015-11-05T15:46:40Z" finished-at="2015-11-05T15:46:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4310d43]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fetchSuiteConfiguration -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.zinghr.login.index.LoginIndex@6aaa5eb0]" name="setUp" is-config="true" duration-ms="35448" started-at="2015-11-05T15:46:40Z" finished-at="2015-11-05T15:47:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.zinghr.login.index.LoginIndex.purchaseFreeCourseForMySelfFunctionality()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4310d43]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="purchaseFreeCourseForMySelfFunctionality()[pri:0, instance:com.zinghr.login.index.LoginIndex@6aaa5eb0]" name="purchaseFreeCourseForMySelfFunctionality" duration-ms="25" started-at="2015-11-05T15:47:16Z" finished-at="2015-11-05T15:47:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.zinghr.login.index.LoginIndex.purchaseFreeCourseForMySelfFunctionality(LoginIndex.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<br> <b>Please look to the screenshot - </b>]]>
            </line>
            <line>
              <![CDATA[<br><Strong><font color=#FF0000>--Failed</font></strong>]]>
            </line>
            <line>
              <![CDATA[<a href='../test-output/screenshots/1105154716486purchaseFreeCourseForMySelfFunctionality.png' target='_new'>1105154716486purchaseFreeCourseForMySelfFunctionality.png</a>]]>
            </line>
            <line>
              <![CDATA[<br></br><h3>Failure Reason:</h3>]]>
            </line>
            <line>
              <![CDATA[<br></br>java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- purchaseFreeCourseForMySelfFunctionality -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.zinghr.login.index.LoginIndex@6aaa5eb0]" name="tearDown" is-config="true" duration-ms="2388" started-at="2015-11-05T15:47:16Z" finished-at="2015-11-05T15:47:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=purchaseFreeCourseForMySelfFunctionality status=FAILURE method=LoginIndex.purchaseFreeCourseForMySelfFunctionality()[pri:0, instance:com.zinghr.login.index.LoginIndex@6aaa5eb0] output=<br> <b>Please look to the screenshot - </b>]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.zinghr.login.index.LoginIndex -->
    </test> <!-- purchase free course for MySelf. -->
  </suite> <!-- NFHS - Purchase_Course_functionality -->
</testng-results>
